services:
  backend:
    container_name: backend
    build:
      context: ./backend-api/simple-api
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
      - SPRING_DATASOURCE_USERNAME=usr
      - SPRING_DATASOURCE_PASSWORD=pwd
    restart: on-failure

  database:
    container_name: database
    build:
      context: ./database
    networks:
      - app-network
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usr -d db"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: on-failure

  httpd:
    container_name: httpd
    build:
      context: ./http-server
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_started
    restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  db-data: